"""baseline schema (idempotent create of any missing tables)

This baseline brings any pre-existing deployment up to the full current schema.
Because earlier versions created tables with ``Base.metadata.create_all`` rather
than migrations, ``upgrade()`` mirrors that behaviour against the migration's
connection: it creates only the tables that are *missing* (e.g. the newer
``favorites``, ``matches`` and ``human_games`` tables) and leaves existing ones
untouched. This makes the migration safe to run on a fresh database (creates
everything) or an established one (adds just the new tables).

Future schema changes should be regular autogenerated migrations
(``alembic revision --autogenerate -m "..."``) chained after this one.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-18
"""
from alembic import op
import sqlalchemy as sa

from db.database import Base
from db import models  # noqa: F401  (register all tables on Base.metadata)

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None

# Tables introduced after the original create_all-based schema; these are the
# ones a previously-deployed database is most likely missing, and the ones this
# revision will drop on downgrade.
_NEW_TABLES = ["matches", "favorites", "human_games"]


def upgrade() -> None:
    bind = op.get_bind()
    # create_all only emits CREATE TABLE for tables that don't already exist,
    # so this is safe on both fresh and established databases.
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    insp = sa.inspect(bind)
    existing = set(insp.get_table_names())
    for table in _NEW_TABLES:
        if table in existing:
            op.drop_table(table)
